# Generated by Django 5.1.6 on 2025-02-26 06:28

import management.validators.image_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(help_text='Please upload an image with equal height and width.', null=True, upload_to='management/menu_items/', validators=[management.validators.image_validator.validate_image]),
        ),
    ]
