# Generated by Django 5.1.6 on 2025-02-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.menuitem'),
        ),
    ]
