# Generated by Django 5.1.6 on 2025-02-25 10:23

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_order_cust_id_alter_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(help_text='Please upload an image which is at least 1280px x 720px.', null=True, upload_to='menu_items/', validators=[management.models.validate_image]),
        ),
    ]
