# Generated by Django 5.1.6 on 2025-02-25 10:41

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(help_text='Please upload an image which is at least 1280px wide x 720px tall.', null=True, upload_to='menu_items/', validators=[management.models.validate_image]),
        ),
    ]
