# Generated by Django 5.1.6 on 2025-03-05 18:57

import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Please upload an image with equal height and width.', null=True, upload_to='menu/menu_items/', validators=[menu.validators.validate_image]),
        ),
    ]
