# Generated by Django 5.1.7 on 2025-04-03 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid 10 digit phone number without country code', regex='^\\d{10}$')]),
        ),
    ]
