# Generated by Django 5.1.7 on 2025-03-11 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(db_column='EMPLOYEE_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=512)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=512, null=True)),
                ('email', models.EmailField(db_column='EMAIL', max_length=512, unique=True)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number in the format XXX.XXX.XXXX', regex='^(\\d{3}.){2}\\d{4}$')])),
                ('hire_date', models.DateField(db_column='HIRE_DATE')),
                ('job_id', models.CharField(db_column='JOB_ID', max_length=512)),
                ('salary', models.IntegerField(db_column='SALARY')),
                ('manager_id', models.IntegerField(blank=True, db_column='MANAGER_ID', null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
    ]
