# Generated by Django 5.1.7 on 2025-03-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True},
        ),
    ]
