# Generated by Django 5.1.7 on 2025-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True, 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.AutoField(db_column='EMPLOYEE_ID', primary_key=True, serialize=False),
        ),
    ]
